version: "3"
services:
  nginx:
    ports:
    - "3000:80"
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
      - MONGO_USER= saeid
      - MONGO_PASSWORD= password
      - SESSION_SECRET=secret
    command: npm run dev  

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=saeid
      - MONGO_INITDB_ROOT_PASSWORD=password 


